"""
app.py – Gradio UI for the Agentic Docs RAG system.

Run:
    python app.py

Optional flags:
    --index   Re-index all documents before launching (use after adding new files).
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import gradio as gr

# ── Logging setup ─────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s – %(message)s",
)
logger = logging.getLogger(__name__)


# ── Lazy globals (initialised once at startup) ────────────────────────────────
_engine = None  # RetrieverQueryEngine


def _init_engine(reindex: bool, project_roots: list[str]) -> None:
    """Initialise the query engine (called once at app startup)."""
    global _engine
    from pipeline import build_index, load_index
    from query_engine import build_query_engine

    if reindex or project_roots:
        if not project_roots:
            logger.warning(
                "No project roots specified for reindexing. "
                "Edit PROJECT_ROOTS in app.py or pass --roots."
            )
        logger.info("Building index from: %s", project_roots)
        index = build_index(project_roots)
    else:
        logger.info("Connecting to existing Pinecone index...")
        index = load_index()

    _engine = build_query_engine(index, top_k=5)
    logger.info("Query engine ready.")


# ── Gradio callback ───────────────────────────────────────────────────────────

def answer_question(question: str, history: list) -> tuple[str, list]:
    """Process a user question and return the answer + updated history."""
    if not question.strip():
        return "", history

    if _engine is None:
        return "⚠️ Engine not initialised yet. Please wait a moment.", history

    from query_engine import query as run_query

    result = run_query(_engine, question)

    # Format the full response with sources
    sources_md = result.format_sources()
    full_answer = f"{result.answer}\n\n---\n**📂 Sources:**\n{sources_md}"

    history.append((question, full_answer))
    return "", history


def get_index_stats() -> str:
    """Return a short status string shown in the UI."""
    try:
        import config
        from pinecone import Pinecone
        pc = Pinecone(api_key=config.PINECONE_API_KEY)
        idx = pc.Index(config.PINECONE_INDEX_NAME)
        stats = idx.describe_index_stats()
        total = stats.get("total_vector_count", "?")
        return f"✅ Pinecone index **{config.PINECONE_INDEX_NAME}** — {total} vectors"
    except Exception as exc:
        return f"⚠️ Could not fetch index stats: {exc}"


# ── Example questions ─────────────────────────────────────────────────────────

EXAMPLES = [
    "What is the main color chosen for the system design?",
    "Are there any recurring technical constraints across documents?",
    "What database schema changes were made recently?",
    "Which component was flagged as problematic or sensitive?",
    "Is there a consistent guideline about RTL support in the UI?",
    "What languages were decided for the interface translations?",
]


# ── Build Gradio interface ────────────────────────────────────────────────────

def build_ui() -> gr.Blocks:
    with gr.Blocks(
        title="Agentic Docs RAG",
        theme=gr.themes.Soft(primary_hue="blue"),
        css=".source-box { font-size: 0.85em; }",
    ) as demo:

        gr.Markdown(
            """
            # 🔍 Agentic Docs RAG
            Ask questions about the documentation generated by your Agentic Coding tools
            (Cursor, Claude Code, Kiro, …).

            The system searches across **all** `.md` files, finds the most relevant chunks,
            and synthesises an answer with citations.
            """
        )

        stats_box = gr.Markdown(value=get_index_stats)

        chatbot = gr.Chatbot(
            label="Conversation",
            height=480,
            show_copy_button=True,
            bubble_full_width=False,
        )

        with gr.Row():
            question_box = gr.Textbox(
                placeholder="Ask anything about your project's AI documentation…",
                label="Your question",
                scale=8,
                autofocus=True,
            )
            send_btn = gr.Button("Send ➤", variant="primary", scale=1)

        gr.Examples(
            examples=EXAMPLES,
            inputs=question_box,
            label="Example questions",
        )

        clear_btn = gr.Button("🗑 Clear conversation", variant="secondary")

        # ── Event wiring ─────────────────────────────────────────────────────
        send_btn.click(
            fn=answer_question,
            inputs=[question_box, chatbot],
            outputs=[question_box, chatbot],
        )
        question_box.submit(
            fn=answer_question,
            inputs=[question_box, chatbot],
            outputs=[question_box, chatbot],
        )
        clear_btn.click(lambda: [], outputs=[chatbot])

    return demo


# ── Entry point ───────────────────────────────────────────────────────────────

# ✏️  Edit this list to point at your own project directories.
PROJECT_ROOTS: list[str] = [
    # "C:/path/to/my-project",
    # "C:/path/to/another-project",
]


def main() -> None:
    parser = argparse.ArgumentParser(description="Agentic Docs RAG — Gradio UI")
    parser.add_argument(
        "--index",
        action="store_true",
        help="Re-index documents before launching.",
    )
    parser.add_argument(
        "--roots",
        nargs="*",
        default=[],
        metavar="PATH",
        help="Project root directories to index (overrides PROJECT_ROOTS in app.py).",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=7860,
        help="Port to run the Gradio server on (default: 7860).",
    )
    args = parser.parse_args()

    roots = args.roots or PROJECT_ROOTS
    _init_engine(reindex=args.index or bool(roots), project_roots=roots)

    demo = build_ui()
    demo.launch(server_port=args.port, share=False)


if __name__ == "__main__":
    main()
